# docker-compose.yml

services:
  trendie:
    image: ankane/pgvector
    container_name: trendie_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    # 비밀번호 설정하는 경우 아래처럼 environment에 추가 가능
    # environment:
    #   REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - trendie
      - redis

  scheduler:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: youtube_scheduler
    restart: always
    environment:
      - PYTHONPATH=/app
    command: [ "python", "app/scheduler/youtube_scheduler.py" ]
    env_file:
      - .env
    depends_on:
      - trendie
      - redis
volumes:
  pgdata:
  redisdata:
